name: cliff
version: 0.1.0
author: whooie
maintainer: wcwhuie@gmail.com
extra-source-files: []
synopsis: ''
description: ''
category: ''
dependencies:
  - base >= 4.7 && < 5
  - random >= 1.2
  - mtl >= 2.3.1
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wno-name-shadowing
  - -Wpartial-fields
  - -Wredundant-constraints
default-extensions:
  - AllowAmbiguousTypes
  - BinaryLiterals
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - GADTSyntax
  - GADTs
  - NamedFieldPuns
  - TupleSections
library:
  source-dirs: lib
# executables:
#   main:
#     main: Main.hs
#     source-dirs: src
#     ghc-options:
#       - -threaded
#       - -rtsopts
#       - -with-rtsopts=-N
#     dependencies: cliff
